title: PL/SE Conference Deadlines
description: This list is heavily biased towards my research topics.<br>I shall not be held liable for any missed deadline due to inaccuracies on this website ;)
author: ThanhVu Nguyen

domain: "https://nguyenthanhvuh.github.io/cs-deadlines/"
baseurl: /cs-deadlines

github_username: nguyenthanhvuh
github_repo: cs-deadlines

markdown: kramdown
#ga_id: UA-36274081-2

theme: jekyll-theme-minimal